"use client";

import React, { useState } from "react";
import clsx from "clsx";
import {
  Database,
  Cpu,
  ArrowUpDown,
  Radio,
  ArrowRight,
  Info,
  CircleAlert,
} from "lucide-react";
import { ScenarioSelector } from "@/client/components/scenarios/ScenarioSelector";
import { AssuranceReport, FindingSeverity } from "@/shared/types/assurance";

const SEVERITY_RANK: Record<FindingSeverity, number> = { CRITICAL: 3, HIGH: 2, MEDIUM: 1, LOW: 0 };

// A category "PASS/WARN/FAIL" badge here is derived from the report's own
// real per-category status string (VERIFIED/COMPROMISED/UNAVAILABLE/etc,
// the same field AssessmentResultCard reads) -- not a separately invented
// score, so this view and the Findings/Report views can never disagree
// about what actually happened in a given category.
function statusToBadge(status: string): "PASS" | "FAIL" | "WARN" {
  const upper = status.toUpperCase();
  if (["VERIFIED", "NORMAL", "MATCH"].includes(upper)) return "PASS";
  if (["COMPROMISED", "TAMPERING_DETECTED", "MISMATCH", "ANOMALOUS"].includes(upper)) return "FAIL";
  return "WARN";
}

interface AssessmentExplorerViewProps {
  title?: string;
  subtitle?: string;
  report?: AssuranceReport | null;
  onInvestigate: () => void;
  activeScenario: string;
  loading: boolean;
  onSelectScenario: (scenarioId: string) => void;
}

/** Shows the real, currently-loaded assessment (either a scenario replay
 * result or a report generated by the New Assessment wizard) -- never a
 * hardcoded demo catalog. Running a different scenario below, or
 * launching a new wizard assessment, changes what's displayed here
 * because both write into the same `report` prop from the parent. */
export const AssessmentExplorerView: React.FC<AssessmentExplorerViewProps> = ({
  title,
  subtitle,
  report = null,
  onInvestigate,
  activeScenario,
  loading,
  onSelectScenario,
}) => {
  const [showLogs, setShowLogs] = useState(false);

  if (!report) {
    return (
      <div className="space-y-6 pb-12 font-sans">
        <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center">
          <p className="text-sm text-slate-500">No assessment loaded yet.</p>
          <p className="text-xs text-slate-400 mt-1">
            Run a scenario below, or create a new assessment from the sidebar.
          </p>
        </div>
        <div className="pt-4 border-t border-slate-200/80">
          <ScenarioSelector
            activeScenario={activeScenario}
            loading={loading}
            onSelectScenario={onSelectScenario}
          />
        </div>
      </div>
    );
  }

  const disposition = report.overall_disposition;
  const statusText =
    disposition === "QUARANTINE" ? "QUARANTINE RECOMMENDED" : disposition === "REVIEW" ? "REVIEW REQUIRED" : "TRUSTED";

  const topDrivers = [...report.findings]
    .sort((a, b) => SEVERITY_RANK[b.severity] - SEVERITY_RANK[a.severity] || b.confidence - a.confidence)
    .slice(0, 6);

  return (
    <div className="space-y-6 pb-12 font-sans">
      {/* Top Assessment Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="font-mono text-xs text-slate-700 bg-slate-100 border border-slate-200 px-2 py-0.5 rounded font-medium">
              {report.report_id}
            </span>
            <span
              className={clsx(
                "font-mono text-xs px-2.5 py-0.5 rounded font-bold border flex items-center gap-1",
                disposition === "REVIEW"
                  ? "bg-amber-50 border-amber-300 text-amber-700"
                  : disposition === "QUARANTINE"
                    ? "bg-rose-100 border-rose-400 text-rose-700"
                    : "bg-emerald-50 border-emerald-300 text-emerald-600"
              )}
            >
              <CircleAlert className="h-3 w-3 inline" />
              {statusText}
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight mt-2">
            {title || report.report_id}
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            {subtitle || `${report.organization} · Problem Statement ${report.problem_statement_id} · Generated ${report.generated_at}`}
          </p>
        </div>

        {/* Overall Assurance Card */}
        <div className="bg-white border border-slate-200/90 rounded-xl px-5 py-3 shadow-xs flex items-center justify-between sm:justify-end gap-5">
          <div className="text-left sm:text-right">
            <div className="font-mono text-[10px] text-slate-400 font-bold uppercase tracking-wider">
              Overall Assurance
            </div>
            <div className="text-xs text-slate-500 font-medium">
              {report.findings.length} finding{report.findings.length === 1 ? "" : "s"}
            </div>
          </div>
          <div className="text-right">
            <span
              className={clsx(
                "text-3xl font-extrabold tracking-tight font-sans",
                disposition === "QUARANTINE" ? "text-rose-600" : disposition === "REVIEW" ? "text-amber-600" : "text-emerald-600"
              )}
            >
              {report.overall_risk_score.toFixed(0)}
            </span>
            <span className="text-xs font-mono text-slate-400 ml-1">/100</span>
          </div>
        </div>
      </div>

      {/* 4 Domain Metric Cards (Bento row) */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: "DATASET", icon: Database, status: report.dataset_assurance_status },
          { label: "MODEL", icon: Radio, status: report.model_assurance_status },
          { label: "INFERENCE", icon: Cpu, status: report.inference_provenance_status },
          { label: "SHIFT", icon: ArrowUpDown, status: report.distribution_shift_status },
        ].map(({ label, icon: Icon, status }) => {
          const badge = statusToBadge(status);
          const isFail = badge === "FAIL";
          return (
            <div
              key={label}
              className={clsx(
                "border rounded-xl p-4 shadow-xs flex flex-col justify-between h-28 transition-all hover:shadow-sm",
                isFail ? "bg-rose-50/40 border-rose-200/90" : "bg-white border-slate-200/90"
              )}
            >
              <div className="flex items-center justify-between">
                <span className={clsx("font-mono text-xs font-bold tracking-wider", isFail ? "text-rose-700" : "text-slate-600")}>
                  {label}
                </span>
                <Icon className={clsx("h-4 w-4", isFail ? "text-rose-600" : "text-slate-500")} />
              </div>
              <div className="flex items-end justify-between">
                <span className={clsx("text-xs font-bold tracking-tight uppercase", isFail ? "text-rose-600" : "text-slate-700")}>
                  {status}
                </span>
                <span
                  className={clsx(
                    "font-mono text-[10px] font-bold px-2 py-0.5 rounded border",
                    badge === "PASS" && "border-sky-300 text-sky-600 bg-sky-50/30",
                    badge === "FAIL" && "border-rose-300 text-rose-600 bg-rose-100/60",
                    badge === "WARN" && "border-amber-300 text-amber-700 bg-amber-50/30"
                  )}
                >
                  {badge}
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Main 2-Column Section (Triggers & Recommended Action) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left: High Confidence Triggers Table */}
        <div className="lg:col-span-8 bg-white border border-slate-200/90 rounded-xl p-5 shadow-xs">
          <div className="flex items-center justify-between pb-3 border-b border-slate-100">
            <h2 className="font-mono text-xs font-bold text-slate-700 uppercase tracking-wide">
              WHY? — PRIMARY RISK DRIVERS
            </h2>
            {report.limitations.length > 0 && (
              <button
                onClick={() => setShowLogs(!showLogs)}
                className="font-mono text-xs text-sky-600 hover:text-sky-700 underline transition-colors cursor-pointer"
              >
                {showLogs ? "Hide Limitations" : "View Coverage Limitations"}
              </button>
            )}
          </div>

          {topDrivers.length === 0 ? (
            <div className="py-8 text-center text-xs text-slate-400">
              No findings raised for this assessment.
            </div>
          ) : (
            <div className="mt-2 overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-100 font-mono text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                    <th className="py-2.5">FINDING</th>
                    <th className="py-2.5">TYPE</th>
                    <th className="py-2.5 text-right">CONFIDENCE</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {topDrivers.map((f) => (
                    <tr key={f.finding_id} className="hover:bg-slate-50/80 transition-colors">
                      <td className="py-3.5 pr-3">
                        <div className="flex items-center gap-2.5">
                          {f.severity === "CRITICAL" || f.severity === "HIGH" ? (
                            <span className="h-3 w-3 rounded-full border-2 border-rose-500 shrink-0" />
                          ) : (
                            <Info className="h-3.5 w-3.5 text-sky-500 shrink-0" />
                          )}
                          <span className="text-slate-800 font-medium text-xs">{f.reason}</span>
                        </div>
                      </td>
                      <td className="py-3.5 font-mono text-slate-600 text-xs">{f.finding_type}</td>
                      <td
                        className={clsx(
                          "py-3.5 text-right font-mono text-xs font-bold",
                          f.severity === "CRITICAL" || f.severity === "HIGH" ? "text-rose-600" : "text-slate-600"
                        )}
                      >
                        {Math.round(f.confidence * 100)}%
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {showLogs && (
            <div className="mt-4 p-3 rounded-lg bg-slate-900 text-slate-200 font-mono text-[11px] leading-relaxed overflow-x-auto space-y-1">
              {report.limitations.map((l, i) => (
                <div key={i}>[LIMITATION {i + 1}] {l}</div>
              ))}
            </div>
          )}
        </div>

        {/* Right: Recommended Action Card */}
        <div
          className={clsx(
            "lg:col-span-4 bg-white border border-slate-200/90 border-t-2 rounded-xl p-5 shadow-xs flex flex-col justify-between",
            disposition === "QUARANTINE" ? "border-t-rose-600" : disposition === "REVIEW" ? "border-t-amber-500" : "border-t-emerald-500"
          )}
        >
          <div>
            <div
              className={clsx(
                "font-mono text-xs font-bold uppercase tracking-wider flex items-center gap-1.5",
                disposition === "QUARANTINE" ? "text-rose-600" : disposition === "REVIEW" ? "text-amber-600" : "text-emerald-600"
              )}
            >
              <span>!</span>
              <span>RECOMMENDED ACTION</span>
            </div>

            <h3 className="font-bold text-base text-slate-900 mt-2">
              {disposition === "QUARANTINE" ? "Quarantine — do not deploy" : disposition === "REVIEW" ? "Review before deployment" : "Approved for deployment"}
            </h3>

            <p className="text-xs text-slate-600 leading-relaxed mt-2">
              {disposition === "QUARANTINE"
                ? "Critical integrity issues require resolution before this asset can be trusted."
                : disposition === "REVIEW"
                  ? "Review the findings below before this asset is deployed."
                  : "No blocking issues found under current coverage."}
            </p>
          </div>

          <div className="mt-6 space-y-2">
            <button
              onClick={onInvestigate}
              className="w-full flex items-center justify-center gap-2 rounded-md bg-slate-900 hover:bg-slate-800 text-white font-mono font-bold text-xs py-3 px-4 uppercase tracking-wider transition-colors shadow-xs cursor-pointer"
            >
              <span>INVESTIGATE</span>
              <ArrowRight className="h-3.5 w-3.5" />
            </button>
          </div>
        </div>
      </div>

      {/* Test Matrix & Vector Replay */}
      <div className="pt-4 border-t border-slate-200/80">
        <ScenarioSelector
          activeScenario={activeScenario}
          loading={loading}
          onSelectScenario={onSelectScenario}
        />
      </div>
    </div>
  );
};
